# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6ZtephBJrFvkEyhzUq7rauFTKGnVtkR
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="EV Resale Value Predictor",
    page_icon="🚗",
    layout="wide"
)

# -----------------------------
# Load Saved Files
# -----------------------------
model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")
encoders = joblib.load("encoders.pkl")
feature_columns = joblib.load("feature_columns.pkl")


# -----------------------------
# Helper Function
# -----------------------------
def encode_input(column, value):
    encoder = encoders[column]
    return encoder.transform([value])[0]

# =============================
# Sidebar
# =============================

st.sidebar.title("🚘 EV Resale Predictor")

st.sidebar.markdown("""
### About

Predict the resale value of an Electric Vehicle using a Machine Learning model.

**Model Used**
- Linear Regression

**Dataset**
Electric Vehicle Analytics Dataset

**Developer**
Prince Bhagat
""")

st.sidebar.success("Ready for Prediction")

st.title("🚗 Electric Vehicle Resale Value Prediction")

st.markdown("""
Predict the estimated resale value of an electric vehicle based on its
technical specifications, battery condition and usage details.

Fill in the vehicle details below and click **Predict Resale Value**.
""")

st.divider()

col1, col2 = st.columns(2)

with col1:

    company = st.selectbox(
        "Company",
        encoders["Company"].classes_
    )

    model_name = st.selectbox(
        "Model",
        encoders["Model"].classes_
    )

    year = st.number_input(
        "Manufacturing Year",
        min_value=2010,
        max_value=2035,
        value=2022
    )

    region = st.selectbox(
        "Region",
        encoders["Region"].classes_
    )

    vehicle_type = st.selectbox(
        "Vehicle Type",
        encoders["Vehicle_Type"].classes_
    )

with col2:

    battery_capacity = st.number_input(
        "Battery Capacity (kWh)",
        min_value=10.0,
        value=60.0
    )

    battery_health = st.slider(
        "Battery Health (%)",
        50,
        100,
        90
    )

    driving_range = st.number_input(
        "Driving Range (km)",
        min_value=50,
        value=350
    )

    charging_power = st.number_input(
        "Charging Power (kW)",
        min_value=1.0,
        value=50.0
    )

    charging_time = st.number_input(
        "Charging Time (hours)",
        min_value=0.5,
        value=2.5
    )

usage_type = st.selectbox(
    "Usage Type",
    encoders["Usage_Type"].classes_
)

charge_cycles = st.number_input(
    "Charge Cycles",
    min_value=0,
    value=500
)

energy_consumption = st.number_input(
    "Energy Consumption (kWh/100km)",
    min_value=5.0,
    value=15.0
)

mileage = st.number_input(
    "Mileage (km)",
    min_value=0,
    value=40000
)

avg_speed = st.number_input(
    "Average Speed (km/h)",
    min_value=10,
    value=55
)

max_speed = st.number_input(
    "Maximum Speed (km/h)",
    min_value=50,
    value=180
)

acceleration = st.number_input(
    "0-100 km/h (seconds)",
    min_value=2.0,
    value=8.5
)

temperature = st.number_input(
    "Average Temperature (°C)",
    value=25.0
)

co2_saved = st.number_input(
    "CO₂ Saved (tons)",
    min_value=0.0,
    value=12.0
)

maintenance_cost = st.number_input(
    "Maintenance Cost (USD)",
    min_value=0.0,
    value=1200.0
)

insurance_cost = st.number_input(
    "Insurance Cost (USD)",
    min_value=0.0,
    value=900.0
)

electricity_cost = st.number_input(
    "Electricity Cost (USD/kWh)",
    min_value=0.0,
    value=0.18
)

monthly_charging_cost = st.number_input(
    "Monthly Charging Cost (USD)",
    min_value=0.0,
    value=60.0
)

st.divider()

if st.button("🚗 Predict Resale Value", use_container_width=True):
    # Data encoding
    company = encode_input("Company", company)
    model_name = encode_input("Model", model_name)
    region = encode_input("Region", region)
    vehicle_type = encode_input("Vehicle_Type", vehicle_type)
    usage_type = encode_input("Usage_Type", usage_type)

    # Create DataFrame from inputs
    input_df = pd.DataFrame([{
        "Company": company,
        "Model": model_name,
        "Year": year,
        "Region": region,
        "Vehicle_Type": vehicle_type,
        "Battery_Capacity_kWh": battery_capacity,
        "Battery_Health_%": battery_health,
        "Range_km": driving_range,
        "Charging_Power_kW": charging_power,
        "Charging_Time_hr": charging_time,
        "Charge_Cycles": charge_cycles,
        "Energy_Consumption_kWh_per_100km": energy_consumption,
        "Mileage_km": mileage,
        "Avg_Speed_kmh": avg_speed,
        "Max_Speed_kmh": max_speed,
        "Acceleration_0_100_kmh_sec": acceleration,
        "Temperature_C": temperature,
        "Usage_Type": usage_type,
        "CO2_Saved_tons": co2_saved,
        "Maintenance_Cost_USD": maintenance_cost,
        "Insurance_Cost_USD": insurance_cost,
        "Electricity_Cost_USD_per_kWh": electricity_cost,
        "Monthly_Charging_Cost_USD": monthly_charging_cost
    }])

    # Filter for feature columns
    input_df = input_df[feature_columns]

    # Scale the data
    scaled_data = scaler.transform(input_df)

    # Make prediction
    prediction = model.predict(scaled_data)[0]

    # Display prediction
    st.success("Prediction Completed!")
    st.metric(
        label="Estimated EV Resale Value",
        value=f"${prediction:,.2f}"
    )

company = encode_input("Company", company)
    model_name = encode_input("Model", model_name)
    region = encode_input("Region", region)
    vehicle_type = encode_input("Vehicle_Type", vehicle_type)
    usage_type = encode_input("Usage_Type", usage_type)

input_df = pd.DataFrame([{
        "Company": company,
        "Model": model_name,
        "Year": year,
        "Region": region,
        "Vehicle_Type": vehicle_type,
        "Battery_Capacity_kWh": battery_capacity,
        "Battery_Health_%": battery_health,
        "Range_km": driving_range,
        "Charging_Power_kW": charging_power,
        "Charging_Time_hr": charging_time,
        "Charge_Cycles": charge_cycles,
        "Energy_Consumption_kWh_per_100km": energy_consumption,
        "Mileage_km": mileage,
        "Avg_Speed_kmh": avg_speed,
        "Max_Speed_kmh": max_speed,
        "Acceleration_0_100_kmh_sec": acceleration,
        "Temperature_C": temperature,
        "Usage_Type": usage_type,
        "CO2_Saved_tons": co2_saved,
        "Maintenance_Cost_USD": maintenance_cost,
        "Insurance_Cost_USD": insurance_cost,
        "Electricity_Cost_USD_per_kWh": electricity_cost,
        "Monthly_Charging_Cost_USD": monthly_charging_cost
    }])

# Handle column name mismatch: rename 'Mileage_km' to 'Total_Distance_Covered_km'
    if 'Mileage_km' in input_df.columns and 'Total_Distance_Covered_km' in feature_columns:
        input_df = input_df.rename(columns={'Mileage_km': 'Total_Distance_Covered_km'})

    # Add 'Vehicle_ID' with a default value if it's a required feature and missing
    if 'Vehicle_ID' in feature_columns and 'Vehicle_ID' not in input_df.columns:
        input_df['Vehicle_ID'] = 0  # Assigning a default value, e.g., 0 or a unique identifier

    # Filter for feature columns, now that 'input_df' should contain all required columns
    input_df = input_df[feature_columns]

scaled_data = scaler.transform(input_df)

prediction = model.predict(scaled_data)[0]

st.success("Prediction Completed!")

    st.metric(
        label="Estimated EV Resale Value",
        value=f"${prediction:,.2f}"
    )