# -*- coding: utf-8 -*-
"""EV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJ_1OpgRw_qkZpKUSSzyDhGmbftjtMZU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/electric_vehicle_analytics.csv')

df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum().sum()

df.duplicated().sum()

df=df.rename(columns={'Mileage_km':'Total_Distance_Covered_km'})

df=df.rename(columns={'Make':'Company'})

numerical_cols = df.select_dtypes(include=np.number).columns

print("Outlier Detection using IQR Method:")
for column in numerical_cols:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

    if not outliers.empty:
        print(f"\nColumn: {column}")
        print(f"  Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
        print(f"  Lower Bound: {lower_bound:.2f}, Upper Bound: {upper_bound:.2f}")
        print(f"  Number of outliers: {len(outliers)}")
        print("  Outlier values (first 5 if many):\n", outliers[[column]].head())
    else:
        print(f"\nColumn: {column}: No outliers detected.")

num_cols = df.select_dtypes(include=np.number).columns

df[num_cols].hist(figsize=(20,18), bins=20)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['Resale_Value_USD'], bins=30, kde=True)
plt.title("Distribution of Resale Value")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Vehicle_Type')
plt.title("Vehicle Type Distribution")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Region')
plt.title("Region Distribution")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(data=df, x='Company')
plt.xticks(rotation=45)
plt.title("Vehicle Manufacturer Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df,
                x='Battery_Capacity_kWh',
                y='Range_km')
plt.title("Battery Capacity vs Driving Range")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df,
                x='Battery_Health_%',
                y='Resale_Value_USD')
plt.title("Battery Health vs Resale Value")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df,
                x='Charging_Power_kW',
                y='Charging_Time_hr')
plt.title("Charging Power vs Charging Time")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df, x='Total_Distance_Covered_km', y='Range_km')
plt.title("Total Distance vs Driving Range")
plt.show()

plt.figure(figsize=(10,5))
sns.boxplot(data=df,
            x='Vehicle_Type',
            y='Resale_Value_USD')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(16,12))

sns.heatmap(df.select_dtypes(include=np.number).corr(),
            annot=True,
            cmap='coolwarm',
            fmt='.2f')

plt.title("Correlation Heatmap")
plt.show()

df.drop('Vehicle_ID', axis=1)

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['Company', 'Model', 'Region', 'Vehicle_Type', 'Usage_Type']

encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

df.head()

X = df.drop('Resale_Value_USD', axis=1)
y = df['Resale_Value_USD']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

import joblib
from sklearn.ensemble import RandomForestRegressor

# Initialize and train the RandomForestRegressor model if it hasn't been defined yet.
# This assumes X_train and y_train are available from previous steps.
rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=4,
    random_state=42
)
rf.fit(X_train, y_train)

# Save trained model
joblib.dump(rf, "model.pkl")

# Save scaler
joblib.dump(scaler, "scaler.pkl")

# Save all label encoders
joblib.dump(encoders, "encoders.pkl")

print("All files saved successfully!")

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
y_pred_lr = lr.predict(X_test)
mse_lr = round(mean_squared_error(y_test, y_pred_lr),2)
r2_lr = round(r2_score(y_test, y_pred_lr),2)
mae_lr = round(mean_absolute_error(y_test, y_pred_lr),2)
rmse_lr = round(root_mean_squared_error(y_test, y_pred_lr),2)

print("Linear Regression Test Data Metrics:")
print(f"MSE: {mse_lr}")
print(f"R²: {r2_lr}")
print(f"MAE: {mae_lr}")
print(f"RMSE: {rmse_lr}")

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error

# Predictions on training data
y_train_pred = lr.predict(X_train)

# Calculate training metrics
mse_train = round(mean_squared_error(y_train, y_train_pred), 2)
r2_train = round(r2_score(y_train, y_train_pred), 2)
mae_train = round(mean_absolute_error(y_train, y_train_pred), 2)
rmse_train = round(root_mean_squared_error(y_train, y_train_pred), 2)

# Display results
print("Linear Regression Training Metrics:")
print(f"MSE: {mse_train}")
print(f"R²: {r2_train}")
print(f"MAE: {mae_train}")
print(f"RMSE: {rmse_train}")

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

dt = DecisionTreeRegressor(
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("Decision Tree Test Metrics")
print("MSE:", round(mean_squared_error(y_test, y_pred_dt),2))
print("R²:", round(r2_score(y_test, y_pred_dt),2))
print("MAE:", round(mean_absolute_error(y_test, y_pred_dt),2))
print("RMSE:", round(np.sqrt(mean_squared_error(y_test, y_pred_dt)),2))

y_pred_dt = dt.predict(X_train)

print("Decision Tree Training Metrics")
print("MSE:", round(mean_squared_error(y_train, y_pred_dt),2))
print("R²:", round(r2_score(y_train, y_pred_dt),2))
print("MAE:", round(mean_absolute_error(y_train, y_pred_dt),2))
print("RMSE:", round(np.sqrt(mean_squared_error(y_train, y_pred_dt)),2))

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=4,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest")
print("MSE:", round(mean_squared_error(y_test, y_pred_rf),2))
print("R²:", round(r2_score(y_test, y_pred_rf),2))
print("MAE:", round(mean_absolute_error(y_test, y_pred_rf),2))
print("RMSE:", round(np.sqrt(mean_squared_error(y_test, y_pred_rf)),2))

y_pred_rf = rf.predict(X_train)

print("Random Forest")
print("MSE:", round(mean_squared_error(y_train, y_pred_rf),2))
print("R²:", round(r2_score(y_train, y_pred_rf),2))
print("MAE:", round(mean_absolute_error(y_train, y_pred_rf),2))
print("RMSE:", round(np.sqrt(mean_squared_error(y_train, y_pred_rf)),2))

y_pred_dt_test = dt.predict(X_test)
y_pred_rf_test = rf.predict(X_test)

metrics_data = {
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest'],
    'MSE': [mse_lr, round(mean_squared_error(y_test, y_pred_dt_test), 2), round(mean_squared_error(y_test, y_pred_rf_test), 2)],
    'R2': [r2_lr, round(r2_score(y_test, y_pred_dt_test), 2), round(r2_score(y_test, y_pred_rf_test), 2)],
    'MAE': [mae_lr, round(mean_absolute_error(y_test, y_pred_dt_test), 2), round(mean_absolute_error(y_test, y_pred_rf_test), 2)],
    'RMSE': [rmse_lr, round(np.sqrt(mean_squared_error(y_test, y_pred_dt_test)), 2), round(np.sqrt(mean_squared_error(y_test, y_pred_rf_test)), 2)]
}

metrics_df = pd.DataFrame(metrics_data)
print(metrics_df)

# Calculate training metrics for Decision Tree
mse_dt_train = round(mean_squared_error(y_train, dt.predict(X_train)), 2)
r2_dt_train = round(r2_score(y_train, dt.predict(X_train)), 2)
mae_dt_train = round(mean_absolute_error(y_train, dt.predict(X_train)), 2)
rmse_dt_train = round(np.sqrt(mean_squared_error(y_train, dt.predict(X_train))), 2)

# Calculate training metrics for Random Forest
mse_rf_train = round(mean_squared_error(y_train, rf.predict(X_train)), 2)
r2_rf_train = round(r2_score(y_train, rf.predict(X_train)), 2)
mae_rf_train = round(mean_absolute_error(y_train, rf.predict(X_train)), 2)
rmse_rf_train = round(np.sqrt(mean_squared_error(y_train, rf.predict(X_train))), 2)

training_metrics_data = {
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest'],
    'MSE_Train': [mse_train, mse_dt_train, mse_rf_train],
    'R2_Train': [r2_train, r2_dt_train, r2_rf_train],
    'MAE_Train': [mae_train, mae_dt_train, mae_rf_train],
    'RMSE_Train': [rmse_train, rmse_dt_train, rmse_rf_train]
}

training_metrics_df = pd.DataFrame(training_metrics_data)
print(training_metrics_df)

feature_importances = rf.feature_importances_
importance = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})
importance = importance.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10,6))
plt.barh(importance["Feature"], importance["Importance"])
plt.gca().invert_yaxis()
plt.title("Feature Importance")
plt.xlabel("Importance")
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred_lr, alpha=0.7)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color='red', linestyle='--')

plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Linear Regression: Actual vs Predicted")
plt.show()

residuals = y_test - y_pred_lr

plt.figure(figsize=(6,4))
plt.scatter(y_pred_lr, residuals, alpha=0.7)
plt.axhline(y=0, color='red', linestyle='--')

plt.xlabel("Predicted Price")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

import joblib

joblib.dump(X.columns.tolist(), "feature_columns.pkl")