# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jn3H4qr88SVnnwz15yMobTwoqt8wkNw6
"""

from fastapi import FastAPI
import joblib
import numpy as np

app = FastAPI()

model = joblib.load("model.pkl")


@app.get("/")
def home():
    return {"message": "ML model API is running"}


@app.post("/predict")
def predict(features: list[float]):

    X = np.array(features).reshape(1, -1)

    prediction = model.predict(X)

    return {
        "prediction": prediction.tolist()
    }